### PR TITLE
Removed ident module

### PR DESCRIPTION
**Pull request by stelcheck**
Removing for the 1.4 release.

### CODE REVIEW

**Comment by ronkorving** [comment]
I'm perfectly happy with this, but I believe @AlmirKadric may have some reservations?

**Comment by AlmirKadric** [comment]
if the auth module does everything the ident module did, i have no issues 👍

**Comment by ronkorving** [comment]
@AlmirKadric It doesn't. If it were identical I wouldn't have built it :)

What it does do, is documented [here](https://github.com/mage/mage/tree/master/lib/modules/auth).

**Comment by stelcheck** [comment]
@AlmirKadric still waiting for feedback on this one.

**Comment by stelcheck** [comment]
@AlmirKadric feel free to go through this repository git history and pull back the code to externalize it if you ever feel the need for it.

**Pull request merged**
