### PR TITLE
Add support for macOS in travis

### LINKED ISSUE #12: Run Travis tests on MacOS
https://docs.travis-ci.com/user/osx-ci-environment/

### PR DESCRIPTION
**Pull request by ronkorving**
Closes #12

### CODE REVIEW

**Comment by stelcheck** [comment]
Could you also rename the text on the badge from Linux to something like "Linux / macOS", like so:

[Build Status: Linux & macOS](https://travis-ci.org/mage/mage)

**Comment by stelcheck** [comment]
Also (unrelated), a message from coveralls on each commit pushed is a bit loud. Any way we could set this to something more unreasonable, such as sending a message only when coverage goes down?

**Comment by ronkorving** [comment]
It's not just each commit I think. We run coveralls for each Node version! That's one reason why at first, I had travis.yml "scripts" section run all node versions one-by-one.

**Comment by stelcheck** [comment]
We should maybe make a separate job for the coverage then - and even there, I would try to make it so not to get notifications unless we have a drop in coverage. We already have GitHub integrated notification markers when tests are failing, adding an explicit message seems redundant in most cases.

**Comment by ronkorving** [comment]
Drop in coverage beyond 0.5% now constitutes failure. I've turned off messages.

**Pull request merged**
