### PR TITLE
Added change password feature to MAGE

### PR DESCRIPTION
**Pull request by Brunni132**
```
auth.register(state, username, password, options, function (error, userId) {
	auth.changePassword(state, username, newPassword, function (error) {
		auth.login(state, username, newPassword, function (error, session) {
			// Profit
		});
	});
});
```

### CODE REVIEW

**Comment by ronkorving** [comment]
Looks good! Could you also add this new method to the ReadMe in this folder?

**Comment by stelcheck** [comment]
@ronkorving shouldn't it go in the user doc instead perhaps? https://mage.github.io/mage/#auth-module

**Comment by Brunni132** [comment]
Yup thanks guys! I'll do all that.
Btw was wondering, is there any limitation to the passwords currently in MAGE? Or in Kakegurui or any depending project? I haven't tested but looking at the code it would look like '' is a perfectly valid password??

**Comment by stelcheck** [comment]
I don't think the auth module sets any limitations, if thats what you mean

**Comment by Brunni132** [comment]
OK thanks!

Not exactly sure what you mean about the ReadMe, and what you would like to see and where. I added the documentation in the mage.ts, so that it would appear online and can be used from typescript. Please tell me if that's not enough.

**Comment by stelcheck** [comment]
I would add usage documentation to https://mage.github.io/mage/#auth-module as well for completeness. This documentation is generated from https://github.com/mage/mage/blob/master/docs-sources/includes/_Actors.md#auth-module

**Comment by Brunni132** [comment]
OK. I didn't bother because I didn't really grasp how doc is supposed to be organized.

In any case this section (mage-auth) is far from being comprehensive, isn't it? It only shallowly covers logging in (not register or what), and I fail to see where that process is described. Shouldn't that go along?

**Pull request merged**
