### PR TITLE
Enhances coverage of config and removes a few redundant code paths.

### PR DESCRIPTION
**Pull request by qubyte**
It looked like my patchy old unit tests could use some enhancements, so that's exactly what I did. This is still rather flat and haphazard though, so if you'd prefer testing of methods in different sub-describes then let me know.

### CODE REVIEW

**Comment by qubyte** [comment]
Not sure what the AppVeyor breakage is about.

**Comment by qubyte** [comment]
0.2%

Really getting stuck into the low hanging fruit. 🤣

**Comment by qubyte** [comment]
By the way... Given that mage is tested on Node 4 and up, what is your policy on supported ES2015 features?

**Comment by stelcheck** [comment]
The Appveyor failure is because you do not have the Appveyor config file  which is in PR #11 right now.

**Comment by ronkorving** [comment]
@qubyte Hey, first of all, thanks for contributing, that's really cool :)

With regards to what language features you can use. You may use most language features the lowest common denominator (Node 4) supports (in fact, it's encouraged), which is quite a lot. I do ask in those cases that you mark the files to `'use strict';`.

What I do want to discourage is using language features "because we can". The reader of the code comes first, performance comes second, clever trickery comes.. well, it's not on the list ;)

**Comment by ronkorving** [comment]
#11 has been merged by the way

**Comment by qubyte** [comment]
I'll rebase on master to fix the appveyor breakage.

Agreed on all counts about usage of features! The reason I ask in this case is because there are a few places which would definitely benefit. For example, this:

```javascript
var joinKeys = Object.keys(a.value);
var bKeys = Object.keys(b.value);

// Add keys from b.value that were not present in a.value;
for (var i = 0; i < bKeys.length; i++) {
	var bKey = bKeys[i];

	if (joinKeys.indexOf(bKey) === -1) {
		joinKeys.push(bKey);
	}
}
```

is more succinctly expressed in a Node 4 and above compatible way as:

```javascript
const aKeys = Object.keys(a.value);
const bKeys = Object.keys(b.value);

// A union of unique keys from a.value and b.value.
const joinKeys = Array.from(new Set(aKeys.concat(bKeys)));
```

I can open a follow-up PR with suggestions soon.

**Comment by ronkorving** [comment]
@qubyte Ah yes, that code is example is rather on the edge for now :) I don't particularly mind that remaining old-style.

**Comment by qubyte** [comment]
I'd go the route of a function to name what's going on there.

**Comment by qubyte** [comment]
Or, given that we don't actually need that to be an array...

```javascript
function mergeObjects(a, b) {
	const aKeys = Object.keys(a.value);
	const bKeys = Object.keys(b.value);
	const joinKeys = new Set(aKeys.concat(bKeys));
	const returnObj = {};

	// Compare each key-by-key.
	for (const key of joinKeys) {
		returnObj[key] = merge(a.value[key], b.value[key]);
	}

	// Make a new matryoshka with the results.
	return new Matryoshka(returnObj, a.source, true);
}
```

**Comment by qubyte** [comment]
Ouch, sorry about that.

**Comment by ronkorving** [comment]
Don't forget 'use strict' at the top of the file (or your const iteration will break on Node 4)

**Comment by ronkorving** [comment]
Superseded by #17

**Pull request closed without merging**
